# -*- coding: utf-8 -*-
"""Ejercicios_Python_Algoritmo_Oviedo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHW3rztE24NGO-F7o4Z1Nx6QPNRpaj4g
"""

opc = 1
while (0<=opc<=8):
  print("\nopc = 1, Suma de dos nros")
  print("\nopc = 2, mayor entre dos nros")
  print("\nopc = 3, Hola Mundo!")
  print("\nopc = 4, Area de triangulo")
  print("\nopc = 5, positivo? negativo? cero?")
  print("\nopc = 6, contar de 1 a 10")
  print("\nopc = 7, promedio de 3 nros")
  print("\nopc = 8, calif. de examen")
  print("\nopc = 0, Salir\n")

  opc = int(input("\ningrese un valor para ver cada ejercicio:"))
  while not(0<=opc<=8):
    print("Ingrese un valor valido entre 0 y 8 por favor!")
    opc = int(input("\ningrese un valor para ver cada ejercicio:"))

  if opc == 0:
    break
  elif opc == 1:
    nro1 =  int(input("Ingrese un valor: \n"))
    nro2 =  int(input("\nIngrese otro valor: \n"))
    suma = nro1 + nro2
    print(f"\nEl valor de la suma entre {nro1} y {nro2} es : {suma}\n")

  elif opc == 2:
    nro1 =  int(input("\nIngrese un valor: \n"))
    nro2 =  int(input("\nIngrese otro valor: \n"))
    if nro1 == nro2:
      print("\nSon iguales los numeros\n")
    elif nro1 > nro2:
      print(f"\nel {nro1} es mayor a {nro2}\n")
    else:
      print(f"\nel {nro2} es mayor a {nro1}\n")


  elif opc == 3:
    print("\nHola mundo!!\n")

  elif opc == 4:
    base = float(input("\nIngrese el valor de la base del triangulo: "))
    altura= float(input("\nIngrese el valor de la altura de dicho triangulo: "))
    area = base * altura / 2
    print(f"\nsiendo la altura {altura} cm y su base {base} cm, su area es {area} cm2")

  elif opc == 5:
    nro= int(input("\nIngrese una valor numerico: "))
    if nro == 0:
      print(f"\nSu nro: {nro} es 0")
    elif nro > 0:
      print(f"\nSu nro: {nro} es mayor a 0 por lo tanto es positivo")
    else:
      print(f"\nSu nro: {nro} es menor a 0 por lo tanto es negativo")

  elif opc == 6:
    for i in range(1,11):
      print(i)

  elif opc == 7:
    nro1= int(input("\nIngrese una valor numerico: "))
    nro2= int(input("\nIngrese otro valor numerico: "))
    nro3= int(input("\nIngrese el tercer valor numerico: "))
    prom = (nro1+nro2+nro3) / 3
    print(f"\nla suma de {nro1}, {nro2}, {nro3} es: {prom}")

  elif opc == 8:
    nota= int(input("\nIngrese su calificacion"))
    while (1>nota or nota >10):
      print("Ingrese una calificacion valida:[1-10]: ")
      nota=int(input("\nIngrese su calificacion: \n"))
    if nota >= 6:
      print("\nUsted aprobo su examen\n")
    else:
      print("\nSu Examen esta desaprobado:\n")