# -*- coding: utf-8 -*-
"""Actividad_Alg_5-05_Oviedo_Alejo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZLIXMT1JIGLI6495IlqspLoI_fYKpzK0
"""

#EJERCICIO1

def ejercicio1(num):
  if num == 0:
    print("Su nro es 0")
  else:
    if num > 0:
      print("Su nro es positivo")
    else:
      print("Su nro es negativo")


numero=int(input("Ingrese el valor que desea comprobar: "))
ejercicio1(numero)

#Ejercicio2

edad = int(input("Ingrese su edad: "))
if edad >= 16:
  print("Usted puede votar")
else:
  print("Usted no puede votar")

#Ejercicio3
nota = float(input("Ingrese su calificacion:"))
if nota >= 6:
  print("Usted esta aprobado")
else:
  print("Usted esta desaprobado")

#Ejercicio4
nombre = "PEPE"
contra = "ABCD123"
nombre1 = str(input("Ingrese su nombre de cuenta:"))
contra1 = str(input("Ingrese su contraseña de la cuenta:"))

if ((nombre == nombre1) and ( contra == contra1)):
  print("Acceso autorizado")
else:
  print("Acceso denegado")

#Ejercicio5
tmp = float(input("Ingrese la temperatura:"))
if tmp >= 22:
  print("Temperatura alta")
elif tmp >=15:
  print("Temperatura agradable")
elif tmp >= 8:
  print("Temperatura baja")
elif tmp >=-10:
  print("Temperatura muy baja")

#Ejercicio6
res = 0
n = 1
while n <= 10:
  num=int(input("Ingrese el valor que desea sumar: "))
  res = res + num
  n += 1
print("El resultado es:",res)

#Ejercicio7
total_n = 0
n = 1
cant_n = int(input("Ingrese la cantidad de notas que desea subir: "))
while n <= cant_n:
  nota = float(input("Ingrese la nota: "))
  total_n += nota
  n += 1
  res = (total_n / cant_n)
print("Su promedio de notas es:",res )

#Ejercicio8
n = 1
num= int(input("Ingrese el valor que desea obtener la tabla de 1 a 10: "))
while n <= 10:
  mult = n * num
  print(f"{n} x {num} = {mult}")
  n += 1